import { allSettled, fork, serialize } from 'effector';

import Head from 'next/head';
import Image from 'next/legacy/image';
import { Todo } from '@/shared/api';

import { model as todoModel, TodosList } from '@/widgets/todos';
import { model as usersModel, UsersList } from '@/widgets/users';
import styles from './home.module.scss';

// type InitialType = {
//   initialState: Todo[];
// };

const Home = () => {
  return (
    <>
      <Head>
        <title>Next practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Home page</h1>
        <Image src="https://i.imgur.com/t7iUoMw.jpeg" alt="Дбрутр" width={30} height={30} priority />

        <div className={styles.wrapper}>
          <TodosList />
          <UsersList />
        </div>
      </main>
    </>
  );
};

export const getServerSideProps = async () => {
  const scope = fork();

  await allSettled(todoModel.getTodos, {
    scope,
  });

  await allSettled(usersModel.getUsers, {
    scope,
  });

  const scopeData = serialize(scope);

  return {
    props: {
      initialState: scopeData,
    },
  };
};

export default Home;
