import Head from 'next/head';

import styles from './home.module.scss';
import Image from 'next/legacy/image';
import { GetServerSideProps, NextPage } from 'next';
import { allSettled, fork, serialize } from 'effector';
import { getTodosFx, Todos } from '@/shared/api';
import { model } from '@/features/todos';

const Home: NextPage<Todos> = ({ todos }) => {
  // const [todos] = useUnit([model.$todos]);
  return (
    <>
      <Head>
        <title>Next practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Home page</h1>
        <Image src="https://i.imgur.com/t7iUoMw.jpeg" alt="Дбрутр" width={30} height={30} priority />

        <div className={styles.wrapper}>
          <div className={styles.todos}>
            {todos &&
              todos.map((todo) => (
                <div key={todo.id}>
                  <h2>{todo.title}</h2>
                  <p>{JSON.stringify(todo.completed)}</p>
                  <br />
                </div>
              ))}
          </div>
          <div className={styles.users}></div>
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<Todos> = async () => {
  const scope = fork();
  const event = model.getTodos;
  await allSettled(event, { scope });
  const scopeData = serialize(scope);
  console.log(scopeData);
  return {
    props: {
      todos: [],
    },
  };
};

export default Home;
