import Head from 'next/head';

import styles from './home.module.scss';
import Image from 'next/legacy/image';

const Home = () => {
  return (
    <>
      <Head>
        <title>Next practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Home page</h1>
        <Image src="https://i.imgur.com/t7iUoMw.jpeg" alt="Дбрутр" width={500} height={300} priority />
      </main>
    </>
  );
};

export default Home;
